### ISSUE TITLE
Feature: Changelog Path as Input

### ISSUE THREAD

**Issue by phanlezz** [rasmus-saks/release-a-changelog-action#2]
## New input for the GitHub action to define CHANGELOG path

As a developer, I want to be able to use this action in a monorepo with multiple releases and changelogs.

#### Feature Request

New input: `path` to specify which/where the CHANGELOG file is

Example:
```
jobs:
  release_a_changelog:
    name: Release a Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release a Changelog
        uses: rasmus-saks/release-a-changelog-action@v1.0.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          path: 'path/to/my/CHANGELOG.md'
```

> If input is not provided it should default to the currently implemented path (./CHANGELOG.md)
